[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
tradetable = "FRtW8QWScLWgDSwSWxnRTBhD8kMXg82aLV2qA3WCtXq3"

[programs.localnet]
tradetable = "FRtW8QWScLWgDSwSWxnRTBhD8kMXg82aLV2qA3WCtXq3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/tradetable.ts"
